FROM elasticsearch:5.5.2
ARG proxy

RUN curl -XGET https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-phonetic/analysis-phonetic-5.5.2.zip. `echo $proxy | sed 's/\(\S\S*\)/--proxy \1/'` > /tmp/analysis-phonetic-5.5.2.zip
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///tmp/analysis-phonetic-5.5.2.zip

