version: '2'

networks:
  default:
    external:
      name: ${DC_NETWORK}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    command:
      - /bin/bash
      - -c
      - |
        if [ ! -z "$http_proxy" ]; then
          host=$${http_proxy##*//};
          host=$${host%%:*};
          port=$${http_proxy##*:};
          (echo -e "cluster.name: \"docker-cluster\"\nnetwork.host: 0.0.0.0\ns3.client.default.proxy.host: $${host}\ns3.client.default.proxy.port: $${port}"  > /usr/share/elasticsearch/config/elasticsearch.yml);
        fi;
        exec /usr/local/bin/docker-entrypoint.sh elasticsearch
    container_name: ${DC_PREFIX}-elasticsearch
    environment:
      - cluster.name=matchid-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS
      - http_proxy
      - https_proxy
      - no_proxy
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: %MM
    volumes:
      - ${ES_DATA}/node1:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9200


