version: '2'

networks:
  default:
    external:
      name: ${DC_NETWORK}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    command:
      - /bin/bash
      - -c
      - |
        bin/elasticsearch-plugin install --batch repository-s3
        exec /usr/local/bin/docker-entrypoint.sh elasticsearch
    container_name: ${DC_PREFIX}-elasticsearch
    environment:
      - cluster.name=matchid-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms%M -Xmx%M"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: %MM
    volumes:
      - ${ES_DATA}/node1:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9200


