
  esnode%N:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: ${DC_PREFIX}-esnode%N
    depends_on:
      - elasticsearch
    environment:
      - cluster.name=matchid-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms%M -Xmx%M"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: %MM
    volumes:
      - ${BACKEND}/esdata/node%N:/usr/share/elasticsearch/data


